name: CI/CD Pipeline

on:
  push:
    branches:
      - ws_teste  # Quando houver um push na branch ws_teste, o pipeline será acionado

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Garante que todo o histórico está disponível

      - name: Check if 'descriptions' exists in *.sqlx files
        run: |
          # Verifica se a palavra 'descriptions:' existe em algum arquivo .sqlx no repositório
          if grep -r "type:" --include="*.sqlx" . && grep -r "descriptions:" --include="*.sqlx" .; then
            echo "As palavras 'type:' e 'descriptions:' foram encontradas nos arquivos sqlx."
          else
            echo "As palavras 'type:' e 'descriptions:' NÃO foram encontradas nos arquivos sqlx."
            exit 1  # Falha o pipeline se uma das palavras não for encontrada
          fi

      - name: Merge ws_teste into development
        run: |
          # Configura o repositório e as credenciais para o git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Faz checkout da branch de destino (development)
          git checkout development

          # Atualiza a branch de destino (development) com as últimas mudanças do remoto
          git pull origin development

          # Faz o merge da branch ws_teste para a development
          git merge origin/ws_teste --no-ff -m "Merge ws_teste into development"

          # Empurra as mudanças para o repositório remoto
          git push origin development

