name: CI/CD Pipeline

permissions: write-all  # settings >> security >> Secretes and Variables >> Actions >> PAT_TOKEN. Permite que o GitHub Actions faça alterações nos arquivos do repositório


on:
  push:
    branches:
      - ws_teste

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if 'type:' and 'descriptions:' exist in *.sqlx files
        run: |
          if grep -r "type:" --include="*.sqlx" . && grep -r "descriptions:" --include="*.sqlx" .; then
            echo "As palavras 'type:' e 'descriptions:' foram encontradas nos arquivos sqlx."
          else
            echo "As palavras 'type:' e 'descriptions:' NÃO foram encontradas nos arquivos sqlx."
            exit 1
          fi

      - name: Merge ws_teste into development
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          git checkout development
          git pull origin development
          git merge origin/ws_teste --no-ff -m "Merge ws_teste into development"
          git push origin development

  sync_to_dataform:
    runs-on: ubuntu-latest
    needs: build  # Garante que só roda após o job "build" terminar com sucesso

    steps:
      - name: Checkout código do repositório atual
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Garante que todo o histórico está disponível

      - name: Checkout do repositório de destino (dataform)
        uses: actions/checkout@v2
        with:
          repository: RodrigoKartcheski/dataform  # Substitua pelo repositório correto
          token: ${{ secrets.PAT_TOKEN }}  # Usa o token de acesso (PAT) para permissões no repositório de destino
          path: temp_repo  # Nome sugerido para o repositório temporário
          ref: main  # Garante que a branch 'main' seja a branch que será baixada

      - name: Criar pasta "qa" no repositório de destino
        run: |
          mkdir -p temp_repo/qa  # Garante que a pasta "qa" exista

      - name: Copiar arquivos do diretório "qa" para o repositório "dataform/qa"
        run: |
          cp -r qa/* temp_repo/qa/  # Copia os arquivos para temp_repo/qa/

      - name: Listar arquivos copiados para o repositório temporário
        run: |
          ls -la temp_repo/qa  # Verifica se os arquivos foram copiados corretamente para temp_repo/qa

      - name: Verificar status do repositório
        run: |
          cd temp_repo
          git status  # Mostra o status para verificar se há arquivos para serem commitados

      - name: Configurar nome de usuário e email para o commit
        run: |
          cd temp_repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit e Push das mudanças para o repositório "dataform"
        run: |
          cd temp_repo
          git add -A  # Força a adição de todas as mudanças
          git commit -m "Atualizando arquivos do diretório 'qa' via CI/CD" || true  # Evita erro caso não haja mudanças
          git push origin main  # Altere para a branch correta do repositório destino, se necessário
