name: CI/CD Pipeline

on:
  push:
    branches:
      - ws_teste

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to development
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Merge ws_teste into development
          title: 'Merge ws_teste to development'
          body: 'Automated merge of ws_teste into development'
          base: development  # Define para qual branch vai o PR
          branch: ws_teste    # Define de qual branch o PR será criado
