# Arquivo onde os valores das variáveis são atribuídos.
GIT_COMMITISH = "main"
#PROJECT = "elet-dados-compulsorio-dev"
PROJECT = "dataplex-experience-6133"
REGION = "us-east1"
ZONE = "us-east1-a"
COMPOSER_NAME = "cc-my-project-dev"
COMPOSER_SA_ID = "123456"
BUCKET_OBJECT_PREFIX = "cs"
RP_COMPULSORIO_TRUSTED_ANALISE_PROVISAO = "df_elet_compulsorio_trusted_analise_provisao"
WS_COMPULSORIO_TRUSTED_ANALISE_PROVISAO = "ws_elet_compulsorio_trusted"
RP_COMPULSORIO_REFINED_ANALISE_PROVISAO = "df_elet_compulsorio_refined_analise_provisao"
WS_COMPULSORIO_REFINED_ANALISE_PROVISAO = "ws_elet_compulsorio_refined"
DS_COMPULSORIO_RAW_ANALISE_PROVISAO = "ds_elet_compulsorio_raw_analise_provisao"
TB_MODIFIED_COMPULSORIO_RAW_ANALISE_PROVISAO = "teste_it"