# Arquivo onde os valores das variáveis são atribuídos.
GIT_COMMITISH = "main"
PROJECT = "dataplex-experience-6133"
REGION = "us-east1"
ZONE = "us-east1-a"
COMPOSER_NAME = "cc-my-project-dev"
COMPOSER_SA_ID = "123456"
BUCKET_OBJECT_PREFIX = "cs"
REPOSITORIO = "dataform_trusted"
WORKSPACE = "dataform_workspace_trusted"
